### ISSUE TITLE
xglass.xsd requires excel/sheet

### ISSUE THREAD

**Issue by AirQuick** [oxygenxml/dita-glass#1]
Per [the oxygen doc](https://www.oxygenxml.com/doc/versions/18.0/ug-editor/topics/import-dynamic-conversions.html#import-dynamic-conversions__ul_r4y_5x2_mr), the **sn** parameter for the **excel** Processor is optional.
But `xglass.xsd` requires the **sheet** element.

**Comment by raducoravu** [comment]
Thanks for the input, I agree. I modified the schema to be more permissive.
